### ISSUE TITLE
Some data files are missing

### ISSUE THREAD

**Issue by Ysis0** [nairouz/CVGAE_PR#1]
Hello, author!

 Thank you for providing the code for the article, and I made this error when reproducing your experiment, " FileNotFoundError: [Errno 2] No such file or directory: '. /CVGAE/resultsCora/pretrain/model_pretrain.pk'
"So come to seek your help.

 Is it convenient for you to provide a complete data file?

**Comment by JiaLonghao1997** [comment]
The '. /CVGAE/resultsCora/pretrain/model_pretrain.pk' can be created by the `network.pretrain()` function in main_cora.py.

**Comment by nazila818** [comment]
Hello dear author.
I ran your codes in the Google Colab environment and instead of "cuda:4", I put "cuda:0" and used the pretrain command in the main_cora file. But I got the following error.

"FileNotFoundError: [Errno 2] No such file or directory: './CVGAE/results/Cora/pretrain/log_train.csv'"

please guide me.

**Comment by nazila818** [comment]
I think this error is because the model training is not done properly, but I don't know what to do to solve the problem?

**Comment by nazila818** [comment]
I could run this code in google colab for Cora, acm and dblp datasets. but fow wiki dataset I receive this error:
FileNotFoundError: [Errno 2] No such file or directory: './data/Wiki/tfidf.txt'

Please uplaod this file in github. Thank a lot.

**Comment by nairouz** [comment]
I have added the pretraining weights to reproduce the paper results.
Please check.

**Comment by nairouz** [comment]
@nazila818 I have added the file  './data/Wiki/tfidf.txt'
Thanks for your interest

**Comment by nairouz** [comment]
@Ysis0 @JiaLonghao1997 I have added the pretraining weights to reproduce the paper results.
Thanks for your interest.

**Comment by nazila818** [comment]
Thank you very much, dear professor
I wish you health and success

Best regards


‫‪Nairouz‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۵ ژوئیه ۲۰۲۴
ساعت ۱۳:۳۸ نوشت:‬
